export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_RESET = "LOGIN_RESET"

export const POLL_LIST_REQUEST = "POLL_LIST_REQUEST"
export const POLL_LIST_SUCCESS = "POLL_LIST_SUCCESS"
export const POLL_LIST_ERROR = "POLL_LIST_ERROR"
export const POLL_LIST_RESET = "POLL_LIST_RESET"

export const POLL_ADD_REQUEST = "POLL_ADD_REQUEST"
export const POLL_ADD_SUCCESS = "POLL_ADD_SUCCESS"
export const POLL_ADD_ERROR = "POLL_ADD_ERROR"
export const POLL_ADD_RESET = "POLL_ADD_RESET"

export const POLL_DEL_REQUEST = "POLL_DEL_REQUEST"
export const POLL_DEL_SUCCESS = "POLL_DEL_SUCCESS"
export const POLL_DEL_ERROR = "POLL_DEL_ERROR"
export const POLL_DEL_RESET = "POLL_DEL_RESET"


export const SINGLE_POLL_REQUEST = "SINGLE_POLL_REQUEST"
export const SINGLE_POLL_SUCCESS = "SINGLE_POLL_SUCCESS"
export const SINGLE_POLL_ERROR = "SINGLE_POLL_ERROR"

export const POLL_EDIT_REQUEST = "POLL_EDIT_REQUEST"
export const POLL_EDIT_SUCCESS = "POLL_EDIT_SUCCESS"
export const POLL_EDIT_ERROR = "POLL_EDIT_ERROR"
export const POLL_EDIT_RESET = "POLL_EDIT_RESET"

export const VOTE_REQUEST = "VOTE_REQUEST"
export const VOTE_SUCCESS = "VOTE_SUCCESS"
export const VOTE_ERROR = "VOTE_ERROR"
export const VOTE_RESET = "VOTE_RESET"

export const OPTION_ADD_REQUEST = "OPTION_ADD_REQUEST"
export const OPTION_ADD_SUCCESS = "OPTION_ADD_SUCCESS"
export const OPTION_ADD_ERROR = "OPTION_ADD_ERROR"
export const OPTION_ADD_RESET = "OPTION_ADD_RESET"

export const OPTION_DEL_REQUEST = "OPTION_DEL_REQUEST"
export const OPTION_DEL_SUCCESS = "OPTION_DEL_SUCCESS"
export const OPTION_DEL_ERROR = "OPTION_DEL_ERROR"
export const OPTION_DEL_RESET = "OPTION_DEL_RESET"